// <auto-generated />
namespace Yers.Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AdminLogAddOperIp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdminLogAddOperIp));
        
        string IMigrationMetadata.Id
        {
            get { return "201807080451296_AdminLog-Add-OperIp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
