// <auto-generated />
namespace Yers.Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class VideoAddSummary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VideoAddSummary));
        
        string IMigrationMetadata.Id
        {
            get { return "201809261250037_Video-Add-Summary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
